//! Byte-parity golden test against the Python oracle: valid signatures (all
//! three schemes) verify, and `redact_provider_payload` produces the exact
//! redacted JSON. The signature fixtures were generated by computing real
//! HMACs with the oracle's formulas at a fixed `now`.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;

use serde_json::Value;

use bss_webhooks::{redact_provider_payload, verify_signature, SignatureScheme};

fn golden() -> Value {
    serde_json::from_str(include_str!("webhooks_golden.json")).expect("fixture parses")
}

fn scheme(name: &str) -> SignatureScheme {
    match name {
        "svix" => SignatureScheme::Svix,
        "stripe" => SignatureScheme::Stripe,
        "didit_hmac" => SignatureScheme::DiditHmac,
        other => panic!("unknown scheme {other}"),
    }
}

fn headers_of(v: &Value) -> HashMap<String, String> {
    v.as_object()
        .unwrap()
        .iter()
        .map(|(k, val)| (k.clone(), val.as_str().unwrap().to_string()))
        .collect()
}

#[test]
fn valid_signatures_verify() {
    let g = golden();
    let now = g["now"].as_f64().unwrap();
    let body = g["body_utf8"].as_str().unwrap().as_bytes();

    for case in g["valid"].as_array().unwrap() {
        let sch = scheme(case["scheme"].as_str().unwrap());
        let secret = case["secret"].as_str().unwrap();
        let headers = headers_of(&case["headers"]);
        verify_signature(secret, body, &headers, sch, 300, Some(now))
            .unwrap_or_else(|e| panic!("{:?} should verify: {e}", case["scheme"]));

        // Tamper the body → signature_mismatch.
        let err = verify_signature(secret, b"tampered", &headers, sch, 300, Some(now))
            .expect_err("tampered body must fail");
        assert_eq!(err.code, "signature_mismatch", "{:?}", case["scheme"]);
    }
}

#[test]
fn redaction_matches_oracle() {
    let g = golden();
    for case in g["redaction"].as_array().unwrap() {
        let provider = case["provider"].as_str().unwrap();
        let got = redact_provider_payload(provider, &case["in"]);
        assert_eq!(got, case["out"], "redact({provider})");
    }
}
