//! Byte-parity golden test: replay outputs captured from the Python oracle
//! (`bss_cockpit.postprocess` + `bss_portal_ui.chat_html`). The fixture is
//! generated by feeding representative inputs through the oracle; every rendered
//! string must match exactly.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use serde_json::Value;

use bss_cockpit::postprocess::{strip_channel_markup, strip_reasoning_leakage};
use bss_portal_ui::{render_assistant_bubble, render_chat_markdown, render_tool_pill};

fn golden() -> Value {
    let raw = include_str!("chat_html_golden.json");
    serde_json::from_str(raw).expect("golden fixture parses")
}

fn s<'a>(v: &'a Value, k: &str) -> &'a str {
    v.get(k).and_then(Value::as_str).unwrap_or_default()
}

fn b(v: &Value, k: &str) -> bool {
    v.get(k).and_then(Value::as_bool).unwrap_or(false)
}

#[test]
fn matches_oracle_golden() {
    let g = golden();

    for case in g["strip_channel_markup"].as_array().unwrap() {
        assert_eq!(
            strip_channel_markup(s(case, "in")),
            s(case, "out"),
            "strip_channel_markup({:?})",
            s(case, "in")
        );
    }

    for case in g["strip_reasoning_leakage"].as_array().unwrap() {
        assert_eq!(
            strip_reasoning_leakage(s(case, "in")),
            s(case, "out"),
            "strip_reasoning_leakage({:?})",
            s(case, "in")
        );
    }

    for case in g["render_chat_markdown"].as_array().unwrap() {
        assert_eq!(
            render_chat_markdown(s(case, "in"), b(case, "allow_tables")),
            s(case, "out"),
            "render_chat_markdown({:?}, allow_tables={})",
            s(case, "in"),
            b(case, "allow_tables"),
        );
    }

    for case in g["render_assistant_bubble"].as_array().unwrap() {
        assert_eq!(
            render_assistant_bubble(s(case, "in"), b(case, "error"), b(case, "allow_tables")),
            s(case, "out"),
            "render_assistant_bubble({:?})",
            s(case, "in")
        );
    }

    for case in g["render_tool_pill"].as_array().unwrap() {
        assert_eq!(
            render_tool_pill(s(case, "in")),
            s(case, "out"),
            "render_tool_pill({:?})",
            s(case, "in")
        );
    }
}
